import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import PageHeader from "@/components/common/page-header";
import PageSideBar from "@/components/common/page-sidebar";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <div className="min-h-screen flex flex-col">
          <PageHeader />
          <div className="flex-1">
            <div className="flex flex-row">
              <PageSideBar />
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
